### PR TITLE
Adds placeholder preview buffers for ignored files for #14

### PR DESCRIPTION
**Pull request by xenodium**
Previously discussed in #14, sending implementation PR. 

Enable/disable via `dired-preview-ignored-show-ignored-placeholders`

Hopefully inline with existing package style/arch/spirit, but happy to tweak as needed.

### CODE REVIEW

**Comment by protesilaos** [comment]
Merged. Thank you!

Please let me know if you have assigned copyright to the Free Software Foundation. I am asking because this package is on GNU ELPA. The present patch should be fine though.

**Comment by xenodium** [comment]
> Please let me know if you have assigned copyright to the Free Software Foundation.

I don't, but I have been meaning to do it. Thanks for the reminder to go check it out.

**Comment by protesilaos** [comment]
Okay, good to know! You will need it eventually for any more contributions, because the limit right now is for ~15 lines of non-trivial code.

**Comment by xenodium** [comment]
SG! I've just emailed assign@gnu.org requesting the assignment form.

**Comment by protesilaos** [comment]
> From: xenodium ***@***.***>
> Date: Wed, 17 Jul 2024 04:58:53 -0700
>
> SG! I've just emailed ***@***.*** requesting the assignment form.

Very well!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Pull request merged**
